/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok7;

import java.io.IOException;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class GuiFitur extends javax.swing.JFrame {
    private ControllerFitur controller;
    private String nomorRekening;
    private Atm user;
    /**
     * Creates new form FiturGui
     */
    public GuiFitur() {
        initComponents();
    }
    
    public GuiFitur(String nomorRekening){
        initComponents();
        controller = new ControllerFitur(this,null,null,null,null);
        this.nomorRekening = nomorRekening;
        user = new Atm();
        try {
            getData();
//            outputSaldo.setText("Saldo : Rp."+user.getSaldo());
//            outputHistoryTransaksi.setText(user.getHistori());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        CekSaldo = new javax.swing.JButton();
        jButtonAmbil = new javax.swing.JButton();
        jButtonGantiPin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonTransfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("HOME");

        CekSaldo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CekSaldo.setText("Cek Saldo");
        CekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekSaldoActionPerformed(evt);
            }
        });

        jButtonAmbil.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonAmbil.setText("Tarik");
        jButtonAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmbilActionPerformed(evt);
            }
        });

        jButtonGantiPin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonGantiPin.setText("Ganti Pin");
        jButtonGantiPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGantiPinActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Transaksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonTransfer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonTransfer.setText("Transfer");
        jButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CekSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGantiPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTransfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jButtonAmbil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CekSaldo)
                    .addComponent(jButtonAmbil))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonTransfer))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGantiPin)
                    .addComponent(jButtonLogout))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGantiPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGantiPinActionPerformed
        // TODO add your handling code here:
        new GuiGantiPin(nomorRekening).setVisible(true);
    }//GEN-LAST:event_jButtonGantiPinActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUILogin().setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GuiTarik(nomorRekening).setVisible(true);
    }//GEN-LAST:event_jButtonAmbilActionPerformed

    private void jButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GuiTransfer(nomorRekening).setVisible(true);
    }//GEN-LAST:event_jButtonTransferActionPerformed

    private void CekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekSaldoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GuiCekSaldo(nomorRekening).setVisible(true);
    }//GEN-LAST:event_CekSaldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GuiTransaksi(nomorRekening).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getData() throws ClassNotFoundException, IOException{
        this.user = controller.getDataUser(nomorRekening);
    }
    
    private void refreshFrame(){
        GuiFitur main = new GuiFitur(nomorRekening);
        main.setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFitur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFitur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFitur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFitur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFitur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CekSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAmbil;
    private javax.swing.JButton jButtonGantiPin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTransfer;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
