/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok7;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author choirulandriansyah
 */
public class GuiTransfer extends javax.swing.JFrame {
    
    private ControllerFitur controller;
    private String nomorRekening;
    private Atm user;
    /**
     * Creates new form GuiTransfer
     */
    public GuiTransfer() {
        initComponents();
    }
    
    public GuiTransfer(String nomorRekening){
        initComponents();
        controller = new ControllerFitur(null,this,null,null,null);
        this.nomorRekening = nomorRekening;
        user = new Atm();
        try {
            getData();
//            outputSaldo.setText("Saldo : Rp."+user.getSaldo());
//            outputHistoryTransaksi.setText(user.getHistori());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputRekeningTujuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputNominalTujuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboBoxBankTujuan = new javax.swing.JComboBox<>();
        jButtonTransfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("TRANSFER");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Rekening Tujuan");

        inputRekeningTujuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Nominal");

        inputNominalTujuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Bank Tujuan");

        comboBoxBankTujuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboBoxBankTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "MANDIRI", "BNI", "BRI", "BTN" }));

        jButtonTransfer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonTransfer.setText("Transfer");
        jButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNominalTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonTransfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxBankTujuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputNominalTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxBankTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonTransfer)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferActionPerformed
        // TODO add your handling code here:
        String rekeningTujuan = inputRekeningTujuan.getText();
        String nominalTujuan = inputNominalTujuan.getText();
        String bankTujuan = comboBoxBankTujuan.getItemAt(comboBoxBankTujuan.getSelectedIndex());

        if(controller.isNumber(nominalTujuan)){
            if(user.getSaldo()>= Integer.parseInt(nominalTujuan)){
                try {
                    if(controller.cekNomorRekening(rekeningTujuan)){
                        Atm atmTujuan = controller.getDataTujuan(rekeningTujuan);
                        if(atmTujuan.getBank().equalsIgnoreCase(bankTujuan)){
                            controller.cekTransfer(nomorRekening,
                                Integer.parseInt(nominalTujuan),
                                rekeningTujuan, user.getBank(),
                                bankTujuan, user.getNmNasabah(),
                                atmTujuan.getNmNasabah());
                            JOptionPane.showMessageDialog(this, "Berhasil transfer ke "+atmTujuan.getNmNasabah()+"!");
                            refreshFrame();
                        }else{
                            JOptionPane.showMessageDialog(this, "Bank tujuan tidak sama!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Nomor rekening tujuan tidak terdaftar!");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Saldo Anda tidak cukup!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Isikan nominal berupa angka!");
        }
    }//GEN-LAST:event_jButtonTransferActionPerformed

    private void getData() throws ClassNotFoundException, IOException{
        this.user = controller.getDataUser(nomorRekening);
    }
    
    private void refreshFrame(){
        GuiFitur main = new GuiFitur(nomorRekening);
        main.setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxBankTujuan;
    private javax.swing.JTextField inputNominalTujuan;
    private javax.swing.JTextField inputRekeningTujuan;
    private javax.swing.JButton jButtonTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
