/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok7;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author choirulandriansyah
 */
public class GuiTarik extends javax.swing.JFrame {

    private ControllerFitur controller;
    private String nomorRekening;
    private Atm user;
    /**
     * Creates new form GuiTarik
     */
    public GuiTarik() {
        initComponents();
    }
    
    public GuiTarik(String nomorRekening){
        initComponents();
        controller = new ControllerFitur(null,null,this,null,null);
        this.nomorRekening = nomorRekening;
        user = new Atm();
        try {
            getData();
//            outputSaldo.setText("Saldo : Rp."+user.getSaldo());
//            outputHistoryTransaksi.setText(user.getHistori());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxNominalAmbilTunai = new javax.swing.JComboBox<>();
        jButtonAmbil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nominal2 = new javax.swing.JTextField();
        TarikJumlahLain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Tarik Tunai");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Nominal Tarik");

        comboBoxNominalAmbilTunai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboBoxNominalAmbilTunai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50000", "100000", "200000", "500000", "1000000" }));

        jButtonAmbil.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonAmbil.setText("Tarik");
        jButtonAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmbilActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Tarik Jumlah Lain");

        TarikJumlahLain.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TarikJumlahLain.setText("Tarik Jumlah Lain");
        TarikJumlahLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarikJumlahLainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxNominalAmbilTunai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nominal2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAmbil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TarikJumlahLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxNominalAmbilTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAmbil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nominal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarikJumlahLain))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilActionPerformed
        // TODO add your handling code here:
        String nominal = comboBoxNominalAmbilTunai
        .getItemAt(comboBoxNominalAmbilTunai.getSelectedIndex());
        if(user.getSaldo()>=Integer.parseInt(nominal)){
            try {
                controller.cekTarikTunai(nomorRekening, nominal);
                JOptionPane.showMessageDialog(this, "Berhasil menarik tunai "
                    + "sebesar Rp."+nominal+"!");
                refreshFrame();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Saldo Anda tidak cukup!");
        }
    }//GEN-LAST:event_jButtonAmbilActionPerformed

    private void TarikJumlahLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarikJumlahLainActionPerformed
        // TODO add your handling code here:
        String nominal = nominal2.getText();
        if(user.getSaldo()>=Integer.parseInt(nominal)){
            int limit = 50000;
            int tarikan = Integer.parseInt(nominal);
            int cek = tarikan%limit;
            if(cek == 0){
                try {
                    controller.cekTarikTunai(nomorRekening, nominal);
                    JOptionPane.showMessageDialog(this, "Berhasil menarik tunai "
                        + "sebesar Rp."+nominal+"!");
                    refreshFrame();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(GuiFitur.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nominal tidak sesuai");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Saldo Anda tidak cukup!");
        }
    }//GEN-LAST:event_TarikJumlahLainActionPerformed

    private void getData() throws ClassNotFoundException, IOException{
        this.user = controller.getDataUser(nomorRekening);
    }
    
    private void refreshFrame(){
        GUILogin main = new GUILogin();
        main.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TarikJumlahLain;
    private javax.swing.JComboBox<String> comboBoxNominalAmbilTunai;
    private javax.swing.JButton jButtonAmbil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nominal2;
    // End of variables declaration//GEN-END:variables
}
